name: Mise à jour des données

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'pipeline.py'
      - 'MATCH.csv'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy

      - name: Run pipeline
        run: python pipeline.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add web/data || true
          git commit -m "update data" || echo "no changes"
          git push
